debug: true

minigame-duel-accept-time: 15

blocks-list:
  - stone
  - grass_block
  - dirt
  - cobblestone
  - oak_planks
  - spruce_planks
  - birch_planks
  - jungle_planks
  - acacia_planks
  - dark_oak_planks
  - oak_log
  - spruce_log
  - birch_log
  - jungle_log
  - acacia_log
  - dark_oak_log
  - sand
  - red_sand
  - gravel
  - gold_ore
  - iron_ore
  - coal_ore
  - oak_leaves
  - spruce_leaves
  - birch_leaves
  - jungle_leaves
  - acacia_leaves
  - dark_oak_leaves
  - sponge
  - glass
  - lapis_ore
  - lapis_block
  - dispenser
  - sandstone
  - chiseled_sandstone
  - smooth_sandstone
  - red_sandstone
  - chiseled_red_sandstone
  - smooth_red_sandstone
  - note_block
  - powered_rail
  - detector_rail
  - sticky_piston
  - cobweb
  - grass
  - fern
  - dead_bush
  - seagrass
  - sea_pickle
  - white_wool

#DONT CHANHGE THIS
possible-orientations:
  - ns
  - we


#мир со всеми аренами
arenas-world: world
#высота на которой будут блоки под люками
arenas-replace-blocks-height: 50

ns-locations:
  first-part:
    1:
      x: 3
      z: 1
    2:
      x: 5
      z: 1
    3:
      x: 7
      z: 1
    4:
      x: 9
      z: 1
    5:
      x: 3
      z: -1
    6:
      x: 5
      z: -1
    7:
      x: 7
      z: -1
    8:
      x: 9
      z: -1


  second-part:
    1:
      x: -1
      z: -1
    2:
      x: -3
      z: -1
    3:
      x: -4
      z: -1
    4:
      x: -1
      z: -4
    5:
      x: -1
      z: -3
    6:
      x: -1
      z: -2

we-locations:
  first-part:
    1:
      x: 1
      z: 1
    2:
      x: 3
      z: 1
    3:
      x: 4
      z: 1
    4:
      x: 1
      z: 4
    5:
      x: 1
      z: 3
    6:
      x: 1
      z: 2

  second-part:
    1:
      x: -1
      z: -1
    2:
      x: -3
      z: -1
    3:
      x: -4
      z: -1
    4:
      x: -1
      z: -4
    5:
      x: -1
      z: -3
    6:
      x: -1
      z: -2