blocks-list:
  - DIRT
  - STONE

#DONT CHANHGE THIS
possible-orientations:
  - ns
  - we


#мир со всеми аренами
arenas-world: world
#высота на которой будут блоки под люками
arenas-replace-blocks-height: 50

ns-locations:
  first-part:
    1:
      x: 1
      z: 1
    2:
      x: 3
      z: 1
    3:
      x: 4
      z: 1
    4:
      x: 1
      z: 4
    5:
      x: 1
      z: 3
    6:
      x: 1
      z: 2

  second-part:
    1:
      x: -1
      z: -1
    2:
      x: -3
      z: -1
    3:
      x: -4
      z: -1
    4:
      x: -1
      z: -4
    5:
      x: -1
      z: -3
    6:
      x: -1
      z: -2

we-locations:
  first-part:
    1:
      x: 1
      z: 1
    2:
      x: 3
      z: 1
    3:
      x: 4
      z: 1
    4:
      x: 1
      z: 4
    5:
      x: 1
      z: 3
    6:
      x: 1
      z: 2

  second-part:
    1:
      x: -1
      z: -1
    2:
      x: -3
      z: -1
    3:
      x: -4
      z: -1
    4:
      x: -1
      z: -4
    5:
      x: -1
      z: -3
    6:
      x: -1
      z: -2