name: GuessBlockMiniGame
version: '${version}'
main: me.leopold95.guessblock.GuessBlock
api-version: '1.20'
authors: [Leopold95]
website: https://www.ukr-minecraft-plugin.fun/

depend:
  - DecentHolograms

commands:
  minigame:
    description: Команда міні гры "Відгадай блок"
    aliases:
      - mg
      - guessblock
      - gb

permissions:
  guessblock.*:
    default: op
    description: "Повний доступ до команд"
  guessblock.duel:
    default: op
    description: "Дає змоги визвати на дуєль"
  guessblock.accept:
    default: true
    description: "Дає змоги приняти дуєль"
  guessblock.giveup:
    default: true
    description: "Дає змоги здатися"
  guessblock.setblock:
    default: true
    description: "Дає змоги здатися"
  guessblock.help:
    default: true
    description: "Деталі до плагіну"
